title: "Understanding Statistics"
description: "A blog about everything statistics"
author: "Kalani Hasanthika"
theme: minima
url: "https://khasanthika.github.io"  # Replace <username> with your GitHub username
baseurl: ""  # Leave empty if it's the root project page
